### ISSUE TITLE
Error Domain=NSURLErrorDomain Code=-1005 “The network connection was lost.”

### ISSUE THREAD

**Issue by vijaysanghavi** [AFNetworking/AFNetworking#2546] opened 2015-02-03 10:23 UTC
I am using AFNetworking classes for calling simple http web services please look at my example code,

```javascript
#pragma mark - AFHTTPRequestOperationManager getter

-(AFHTTPRequestOperationManager *)manager
{
    if (!_manager)
    {
        _manager = [AFHTTPRequestOperationManager manager];
        _manager.requestSerializer = [AFHTTPRequestSerializer serializer];
        _manager.responseSerializer = [AFHTTPResponseSerializer serializer];
    }
    
    return _manager;
}

#pragma mark - Web Api Methods

-(void)callMethodWithParameters:(NSDictionary *)parameters success:(RequestCompletionHandlerBlock)success failure:(RequestFailedHandlerBlock)failure
{
    [self.manager POST:BASE_URL parameters:parameters
     
               success:^(AFHTTPRequestOperation *operation, id responseObject)
     {
         NSError *parsingError;
         NSMutableDictionary *responseDict = [NSJSONSerialization JSONObjectWithData:responseObject options:NSJSONReadingMutableContainers error:&parsingError];
         success(responseDict);
     }
     
               failure:^(AFHTTPRequestOperation *operation, NSError *error)
     {
         NSLog(@"Error = %@",error);
         failure(error);
     }];
}
```

When I call the web services for the very first time I get the response what I expected but after calling it once I get the error message **Error Domain=NSURLErrorDomain Code=-1005 “The network connection was lost.”** but I don't get this message all the time sometimes I get correct response but sometimes I get the error message.

***Is this the problem of persistent connection?***
**Please suggest what I can do here?**

**Comment by juzzin** [comment] 2015-02-03 18:45
Encountering the same issue.

**Comment by mattt** [comment] 2015-02-03 21:30
[Restart the simulator](http://stackoverflow.com/questions/25372318/error-domain-nsurlerrordomain-code-1005-the-network-connection-was-lost).

**Comment by vijaysanghavi** [comment] 2015-02-04 05:36
*Greets! Actually I am facing the issue in all my devices iPhone 5s, iPhone 4, iPad Mini, and iPhone 6.*

**Please help**

**Comment by mattt** [comment] 2015-02-04 18:44
Duplicate of #2314.

**Closed by mattt** 2015-02-04 18:44 UTC

**Comment by chrisharrison** [comment] 2015-04-16 07:28
Happening on the device. Not just the simulator.

**Comment by yogendrabagoriya** [comment] 2015-08-19 06:35
Remove "keep-alive" from HTTP Header at server side.

**Comment by yujean** [comment] 2016-04-19 19:50
For what it's worth, I received this error 100% on Alamofire, when I sent an empty dictionary `[:]` on a `GET` request.  The error could have been clearer than "The network connection was lost".

Hope this helps!

**Comment by jnutting** [comment] 2017-10-23 09:37
Thank you @yujean! I spent an hour or two tearing my hair out over this issue, and your simple observation solved it for me.
