### ISSUE TITLE
Docs on Reachability contradict Apple's docs.

### ISSUE THREAD

**Issue by ileitch** [AFNetworking/AFNetworking#2701] opened 2015-05-06 17:30 UTC
In the AFNetworking [docs about Reachability](http://cocoadocs.org/docsets/AFNetworking/2.5.3/):

"Network reachability is a diagnostic tool that can be used to understand why a request might have failed. **It should not be used to determine whether or not to make a request.**"

[Apple's docs](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/URLLoadingSystem/NSURLSessionConcepts/NSURLSessionConcepts.html):

"If the task failed, most apps should retry the request until either the user cancels the download or the server returns an error indicating that the request will never succeed. Your app should not retry immediately, however. Instead, **it should use reachability APIs to determine whether the server is reachable, and should make a new request only when it receives a notification that reachability has changed.**"

Why does AFNetworking recommend against using reachability to determine if it's appropriate to make a request?

**Comment by kcharwood** [comment] 2015-05-06 17:54
My personal experience with Reachability is that I've needed to use it to determine when I definitely **should not** send a request to server. Getting a status of reachable does not guarantee the request I am about to send will actually make it to the destined server, so I should not write code that assumes that. When I get NotReachable, I can be sure ahead of time that it won't make it.

**Comment by taylesworth** [comment] 2015-05-06 17:59
I think the difference is that Apple is talking about how to handle a potential retry after a request has failed. You should never use Reachability to decide whether or not to send the original request. It can be used for diagnostics to determine how to handle failures, for example, whether or not to retry the request immediately.

**Comment by tewha** [comment] 2015-05-06 19:20
Watch any of Apple's sessions; Reachability's docs are incorrect. You must not use Reachability to gate connection attempts.

Or heck, look at Apple's apps.

**Comment by tewha** [comment] 2015-05-06 19:21
@kcharwood: That's the wrong behaviour. If you're told the server is unreachable, it only means that it's not currently unreachable. Attempting it may make it reachable.

**Comment by tewha** [comment] 2015-05-06 19:41
Try 2012 session 706, "Networking Best Practices."

The whole video is great, but you should watch from 32:50. The statement at 32:56 is _very_ clear: "Don't check the Reachability object to determine if something's available. It can be deceptive in some cases. You want to go ahead and just make the attempt anyhow. If you succeed, you're done. If you don't succeed, you want to wait for another Reachability change notification before you attempt again."

Though this is misleading, too: If your UI allows you to add a simple way for the user to indicate they want to try again *now*, like Safari has, you should definitely try again if they tap that rather than just waiting. iOS can be lazy about connections; until something tries networking, it may take a while before the OS notices it *could* connect here and attempts to.

**Comment by kcharwood** [comment] 2015-05-06 21:03
@tewha I think we're saying the same thing, but I am not sure. If I see notreachable, I am not going to send out the request. In addition, when I do see reachable, I can't assume it will actually make it. I need to be prepared for that to still timeout, fail, etc and code for that. Make sense?

**Comment by tewha** [comment] 2015-05-07 02:16
@kcharwood I understood you. You're not doing the right thing.

If Reachability says the server is unreachable, you're supposed to **try anyway**. Because even though Reachability says it **won't** work, it will often be wrong about that and it **will** work.

**Comment by kcharwood** [comment] 2015-05-07 13:32
@tewha That's really interesting. Certainly doesnt match my experience with Reachability. In just about all cases I can remember, trying the request anyway leads to a request that eventually times out, giving a poor user experience.

Have you seen requests work often when reachability declares something as not reachable? Just doesnt seem to match up with the 100+ apps I've been involved with.

**Comment by tewha** [comment] 2015-05-07 16:40
Yup. Happens all the time with Safari on my iPad.

**Comment by taylesworth** [comment] 2015-05-07 18:00
@kcharwood In most cases, you are correct that Reachability is very reliable. However it can and does get confused under some conditions and reports the network as unavailable when it is. I know this first-hand because we unfortunately implemented our mobile app to disable most features when Reachability reported the network as unavailable. We then discovered the edge cases which caused users to be unable to access features even though they clearly had network coverage. 

One of the easiest ways for us to reproduce this was to use the app on an iPhone on WiFi, enter an elevator on a high floor in an office building, put the phone in a pocket while going down to the first floor, exit the building, and then open the app. Around 5% of the time, doing this will not trigger a Reachability notification when the phone connected to the cellular network. It will continue to report network unavailable from losing it during the elevator ride.

That's when I researched more and discovered that Apple recommends against using Reachability to prevent network requests. I also looked at other apps -- Safari, Facebook, Twitter, Google+. None of them prevent users from doing whatever they want when they show a no-network-connected banner. They use Reachability merely to show the banner so users know that they may not be able to use the app. But they still send requests based on user interaction even if they believe they don't have connectivity.

**Comment by ileitch** [comment] 2015-05-07 18:13
Wow, quite a lot of confusion here. My takeaways:

* Do not use Reachability to determine if an **original** request should be sent.
* (optionally) Use Reachability to determine if a request should be retried.
* Reachability is most useful for giving the user ahead of time feedback about connectivity status (e.g a banner). Potentially lessening the annoyance they feel when a request fails.

**Comment by tewha** [comment] 2015-05-07 18:14
Reachability is not "confused." Reachability is doing exactly what it's supposed to do. This is what's so important to understand about Reachability, and it's obvious if you think about the power level involved in networking:

- Reachability will report that unreachable if the networking hardware is powered down.
- Attempting to make a connection will power up the networking hardware.

If you are **relying** on Reachability saying something might be reachable, you are relying on something else (a background process) powering up the networking hardware. There's a number of them in the OS, don't get me wrong, so it's unlikely it'll stay down forever. But many of these processes can be disabled. The result can quite easily be the phone sitting in the middle of a room with beautiful networking, Reachability reporting "not reachable." But if you were to try sending a network request, the hardware would obediently power up, establish a connection, and the request would succeed.

**Comment by ileitch** [comment] 2015-05-07 18:18
Yes, automatic transparent retry is indeed what I meant :)

**Comment by taylesworth** [comment] 2015-05-07 18:18
@tewha Fair enough. However in my experience Reachability can continue to report "not reachable" even when other apps have just used the networking hardware. That was the situation we ran into. Switching to Safari, making a successful web page request, and returning to our app would still claim that our server was unreachable.

@ileitch Yes, your takeaways are spot-on.

**Comment by tewha** [comment] 2015-05-07 18:19
@taylesworth That could be, too. Networking is a mess. :) I wonder if tearing down the Reachability and re-establishing it would have fixed it.

**Comment by taylesworth** [comment] 2015-05-07 18:20
@tewha Probably. Now if only we could have something to indicate when we should re-establish Reachability...  ;-)

**Comment by tewha** [comment] 2015-05-07 18:24
Oh, I thought of one other thing. @kcharwood, this might explain the differences we see. If your app is set to require a persistent WiFi connection, the iOS is likely more aggressive about getting networking back on. I still wouldn't completely trust this, though, as it's probably not as aggressive enough to detect a network connection faster than the user can tap a retry button.

@ileitch's takeaway is still the right approach.

**Comment by kcharwood** [comment] 2015-05-07 18:26
We actually do set that is quite a few of our apps, so that may be a good note worth calling out.

**Comment by fcy** [comment] 2015-05-07 18:29
@ileitch what about a PR to add your takeaways points to AFNetworking docs? (I'm assuming it is possible to open a PR for the docs)

**Comment by tewha** [comment] 2015-05-07 18:29
In any case, I think we can update the docs. Where are they? :)

**Comment by tewha** [comment] 2015-05-07 18:31
Nevermind, found them, I'll fix something up and y'all can see if it needs more work.

**Comment by tewha** [comment] 2015-05-07 18:40
There. I think this definitely needs more work before its merged, and I'll look at it again, but if you guys have any feedback:

https://github.com/AFNetworking/AFNetworking/pull/2704/files

**Comment by mattt** [comment] 2015-05-11 13:24
To address the original issue:

@ileitch The two statements you cited are actually not incompatible. As @taylesworth pointed out, Apple's documentation here is talking about using reachability as a condition for retry, whereas AFNetworking's documentation is making a broader statement that reachability should not be used as a condition for initial request (which is @tewha's point). AFNetworking's not incorrect, _per se_, it could certainly be improved. `AFNetworkReachabilityManager` is one of the more misunderstood components of AFNetworking, and something I've been wanting to address for a while.

Thank you all for your discussion so far. I would encourage you to lend any further insights into #2704, so that we can make those necessary improvements to the documentation.

**Closed by mattt** 2015-05-11 13:24 UTC
Labels: documentation, reachability
