### ISSUE TITLE
Crash , Thread : Crashed: com.apple.CFNetwork.addPersistCacheToStorageDaemon

### ISSUE THREAD

**Issue by rajanikanth05** [AFNetworking/AFNetworking#3240] opened 2015-12-21 15:59 UTC
I'm getting crash similar to https://github.com/AFNetworking/AFNetworking/issues/2866 multiple times in production. DeviceModel : "iPhone7,1" and DeviceOS : "iOS 9.1 (Build 13B143)". 

Below is the stack trace.
Thread : Crashed: com.apple.CFNetwork.addPersistCacheToStorageDaemon
    {
      "StackTrace" : [
        "#0  Inpatient                           0X000000010017ABC8 +[Logging signalHandler:]",
        "#1  Inpatient                           0X0000000100151804 -[NSURL portByScheme]",
        "#2  libsystem_platform.dylib            0X000000019AB1194C _sigtramp()",
        "#3  Foundation                          0X00000001863E6138 NSCopyMemoryPages()",
        "#4  Foundation                          0X00000001863E6138 NSCopyMemoryPages()",
        "#5  Foundation                          0X00000001863C1AE8 -[NSData getBytes:length:]",
        "#6  Foundation                          0X00000001863ECDB4 -[NSData replacementObjectForCoder:]",
        "#7  Foundation                          0X000000018638548C -[NSXPCEncoder _replaceObject:]",
        "#8  Foundation                          0X00000001863EF5E4 -[NSXPCEncoder _encodeArrayOfObjects:forKey:]",
        "#9  Foundation                          0X00000001863EC544 -[NSDictionary encodeWithCoder:]",
        "#10 Foundation                          0X0000000186385E30 -[NSXPCEncoder _encodeObject:]",
        "#11 Foundation                          0X0000000186386318 <redacted>()",
        "#12 Foundation                          0X0000000186385FD8 -[NSXPCEncoder encodeInvocation:]",
        "#13 Foundation                          0X0000000186385E30 -[NSXPCEncoder _encodeObject:]",
        "#14 Foundation                          0X000000018655B198 -[NSXPCConnection _sendInvocation:withProxy:remoteInterface:withErrorHandler:timeout:userInfo:]",
        "#15 CoreFoundation                      0X0000000185534A30 <redacted>()",
        "#16 CoreFoundation                      0X0000000185438CAC _CF_forwarding_prep_0()",
        "#17 CFNetwork                           0X0000000184C81B78 <redacted>()",
        "#18 libdispatch.dylib                   0X000000019A9016E8 <redacted>()",
        "#19 libdispatch.dylib                   0X000000019A9016A8 <redacted>()",
        "#20 libdispatch.dylib                   0X000000019A90D6EC <redacted>()",
        "#21 libdispatch.dylib                   0X000000019A9051AC <redacted>()",
        "#22 libdispatch.dylib                   0X000000019A90F5BC <redacted>()",
        "#23 libdispatch.dylib                   0X000000019A90F2DC <redacted>()",
        "#24 libsystem_pthread.dylib             0X000000019AB15470 _pthread_wqthread()",
        "#25 libsystem_pthread.dylib             0X000000019AB15020 start_wqthread()"
      ]
    }

The crash is sporadic. I enabled zombie and was able to reproduce the crash at some point. It says:
[CFData retain]: message sent to deallocated instance 0x7fe876eeb770
[CFData respondsToSelector:]: message sent to deallocated instance 0x7fe876eeb770

Any help is highly appreciated.

**Comment by kcharwood** [comment] 2016-01-14 14:43
dupe of #2866

**Closed by kcharwood** 2016-01-14 14:43 UTC
