### ISSUE TITLE
baseURL is not used in requestWithMethod:URLString:parameters: as stated in docs

### ISSUE THREAD

**Issue by teradyl** [AFNetworking/AFNetworking#2828] opened 2015-07-07 01:11 UTC
According to the docs:
```
/**
The URL used to monitor reachability, and construct requests from relative paths in methods like requestWithMethod:URLString:parameters:, and the GET / POST / et al. convenience methods.
*/
@property (readonly, nonatomic, strong) NSURL *baseURL;
```
When creating a request using `requestWithMethod:URLString:parameters:error:` (`requestWithMethod:URLString:parameters:` is deprecated), it doesn't take into account the baseURL for the request as stated in the docs.

Only the convenience request methods take advantage of the baseURL. If you want to use `requestWithMethod:URLString:parameters:error:` in your code, you have to construct your URL with the baseURL manually.

In my case, this became an issue since I wanted to funnel all requests through `requestWithMethod` instead of having if-else statements deciding which convenience method to use.

It would seem that making `HTTPRequestOperationWithHTTPMethod:URLString:parameters:success:failure:` a public method would help this problem, enabling the ability to override that directly and calling that instead of `HTTPRequestOperationWithRequest:success:failure:`

**Comment by kcharwood** [comment] 2015-07-09 13:16
Dupe of #2761

**Closed by kcharwood** 2015-07-09 13:16 UTC

**Comment by db42** [comment] 2015-12-15 05:28
This issue is not fixed. Solution for [#2761](https://github.com/AFNetworking/AFNetworking/pull/2761) just modified the documentation.

**Comment by kcharwood** [comment] 2015-12-15 15:22
Thanks @db42. I think I have this all straightened out in the 3.0.0 release, but I'd love a second pair of eyes. The deprecated methods were removed, and I believe everything is going through the same path now.
