### ISSUE TITLE
ITMS-90809: Deprecated API Usage -  UIWebView APIs

### ISSUE THREAD

**Issue by sunlight2728** [AFNetworking/AFNetworking#4505] opened 2020-01-27 10:23 UTC
Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by funnel20** [comment] 2020-02-03 09:33
This refers to Apple News from December 23, 2019 at:
https://developer.apple.com/news/?id=12232019b

The timing:

> The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

**Comment by zhenhuamu** [comment] 2020-02-18 16:14
pod 'AFNetworking/NSURLSession', '3.2.1'
  pod 'AFNetworking/Reachability', '3.2.1'
  pod 'AFNetworking/Security', '3.2.1'
  pod 'AFNetworking/Serialization', '3.2.1'
  可以暂时这样去解决，如果你没有使用AFNetworking/UIKit

**Comment by zhenhuamu** [comment] 2020-02-18 16:15
> Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> 
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> 
> After you’ve corrected the issues, you can upload a new binary to App Store Connect.
> 
> Best regards,
> 
> The App Store Team

  pod 'AFNetworking/NSURLSession', '3.2.1'
  pod 'AFNetworking/Reachability', '3.2.1'
  pod 'AFNetworking/Security', '3.2.1'
  pod 'AFNetworking/Serialization', '3.2.1'
可以暂时这样去解决，如果你没有使用AFNetworking/UIKit

**Comment by hahaGitHub** [comment] 2020-03-03 03:42
我们也收到这个了呢。
我们使用了AFNetworking/UIKit呢，所以咋处理呢？

**Comment by funnel20** [comment] 2020-03-03 07:00
Duplicate of #4428

**Comment by pomegra** [comment] 2020-03-04 03:40
> 我们也收到这个了呢。
> 我们使用了AFNetworking/UIKit呢，所以咋处理呢？

等更新吧，毕竟AFNetworking使用太广泛了，现在是截止2020.12月停止使用UIweb的

**Comment by wz15011015** [comment] 2020-03-04 05:37
坐等更新😀😀

**Comment by ElfSundae** [comment] 2020-03-09 12:37
See https://github.com/AFNetworking/AFNetworking/issues/4428

**Comment by buvtopcc** [comment] 2020-03-10 04:07
临时处理，在podfile中增加pre_install强制删掉UIWebView相关文件，坐等AFNetworking更新
pre_install do |installer|
    puts 'pre_install begin....'
    dir_af = File.join(installer.sandbox.pod_dir('AFNetworking'), 'UIKit+AFNetworking')
    Dir.foreach(dir_af) {|x|
      real_path = File.join(dir_af, x)
      if (!File.directory?(real_path) && File.exists?(real_path))
        if((x.start_with?('UIWebView') || x == 'UIKit+AFNetworking.h'))
          File.delete(real_path)
          puts 'delete:'+ x
        end
      end
    }
    puts 'end pre_install.'
    end
end

**Comment by tjanela** [comment] 2020-03-27 03:58
See #4439

**Comment by Kaspik** [comment] 2020-03-29 22:03
Updated, released. Can be closed.

**Closed** 2020-03-29 22:08 UTC
