### ISSUE TITLE
Property with 'retain (or strong)' attribute must be of object type

### ISSUE THREAD

**Issue by codesourse** [AFNetworking/AFNetworking#2792] opened 2015-06-18 09:13 UTC
#if OS_OBJECT_HAVE_OBJC_SUPPORT
@property (nonatomic, strong) dispatch_queue_t completionQueue;
#else
@property (nonatomic, assign) dispatch_queue_t completionQueue;
#endif

/**
 The dispatch group for `completionBlock`. If `NULL` (default), a private dispatch group is used.
 */
#if OS_OBJECT_HAVE_OBJC_SUPPORT
@property (nonatomic, strong) dispatch_group_t completionGroup;
#else
@property (nonatomic, assign) dispatch_group_t completionGroup;
#endif

IN "@property (nonatomic, strong) dispatch_group_t completionGroup;"
call  "/Pods/AFNetworking/AFNetworking/AFURLConnectionOperation.h:200:1: Property with 'retain (or strong)' attribute must be of object type"

anyone can help me

**Comment by 7934345** [comment] 2015-07-28 07:34
I got the same error, any update now????

**Comment by codesourse** [comment] 2015-07-28 07:38
@property (nonatomic, strong) dispatch_group_t completionGroup;
change to 
@property (nonatomic, assign) dispatch_group_t completionGroup;

**Comment by canius** [comment] 2015-08-31 07:40
Hi guys, are u using pod AFNetworking?

I have made a pull request to fix this issue:
https://github.com/AFNetworking/AFNetworking/pull/2930

Any ideas?

**Comment by dalu93** [comment] 2015-09-05 13:55
I had the same problem, referencing to AFNetworking as below:

    s.dependency 'AFNetworking'

in my lib podspec file. I read about an error due to a circular dependency, but in my code there isn't it.

**Comment by kcharwood** [comment] 2015-10-19 15:40
This should be fixed in the latest version of AFNetworking

**Closed by kcharwood** 2015-10-19 15:40 UTC

**Comment by vkaramov** [comment] 2016-01-06 15:58
I've changed the deployment target of my App to 8.0 and moved to AFNetworking 3.0.4. The issue is still there.

**Comment by prathap2626** [comment] 2018-10-04 06:38
@codesourse If I am changing from strong to assign. it is showing the error as unknown type.
