### ISSUE TITLE
Server response with status code 205 leads to timeout

### ISSUE THREAD

**Issue by bennibau** [AFNetworking/AFNetworking#2797] opened 2015-06-19 11:08 UTC
Our Backend sends at a certain call the response 205 without content (according to HTTP status code specification)
The app waits until the timeout has run out and returns with a timeout. Is the call waiting for content which will not be sent?

**Comment by kcharwood** [comment] 2015-06-26 14:17
[By default](https://github.com/AFNetworking/AFNetworking/blob/2.5.4/AFNetworking/AFURLResponseSerialization.m#L98), code 205 is an acceptable response code and behaves just like any other 2xx code in AFNetworking

**Comment by dgustafsson-dsi** [comment] 2016-01-14 09:13
I am seeing the same behaviour. 
A response with code 205 does not return the success block - The request times out and we get a timeout in the failure block. 
I see that 205 is an acceptable response according to the above. But if it was not acceptable the failure block would be invoked immediately, it would not time out.

There's also a SO post regarding the same here
http://stackoverflow.com/questions/28031209/stuck-in-a-request-with-response-205

**Comment by kcharwood** [comment] 2016-01-14 15:11
What is being returned for your response content type?

**Comment by dgustafsson-dsi** [comment] 2016-01-14 15:32
The AFHTTPRequestOperation's response object is 'nil'.

**Comment by bennibau** [comment] 2016-01-14 15:42
Yep as I said in June, the framework does not come back to the call. It times out even if the server responds correctly.

**Comment by kcharwood** [comment] 2016-01-14 15:43
Sorry. I meant your actually http response headers. Not the cocoa object.

**Comment by bennibau** [comment] 2016-01-14 15:44
sorry I cannot provide details on that anymore since it was long time ago. We changed our backend using another responsecode for that call.

**Comment by dgustafsson-dsi** [comment] 2016-01-14 15:50
The response headers, as in? 
operation.response.allHeaderFields
operation.response is 'nil'
so there are no headers. There is no response.

**Comment by kcharwood** [comment] 2016-01-14 15:59
Sorry. I'm saying if you were to hit with a web request app, or Charles, or postman, etc, what is the full response and all the headers being returned by the server. You won't see that in AF because the response object is nil.

You could dig deeper into NSURLSession and get that information as well.

Alternatively, do you have a public URL i could hit?

**Comment by dgustafsson-dsi** [comment] 2016-01-14 16:08
Ah, got you.
Using Charles I get these response headers

HTTP/1.1 205 Reset Content
Server: Apache-Coyote/1.1
Date: Thu, 14 Jan 2016 16:04:58 GMT

**Comment by kcharwood** [comment] 2016-01-14 16:12
Gotcha. So I'm assuming the problem here is there is no response content type, which causes the response serializer to fail.

I'll need to take a look at this.

**Comment by kcharwood** [comment] 2016-01-14 16:12
Although I'm surprised it's timing out. It should be calling the failure block...

**Comment by dgustafsson-dsi** [comment] 2016-01-14 16:15
Thanks, yes it is a bit surprising that one of the blocks aren't called. We are receiving a response after all.

**Comment by bennibau** [comment] 2016-01-14 16:25
From Wikipedia:
205 Reset Content
The server successfully processed the request, but is not returning any content. Unlike a 204 response, this response requires that the requester reset the document view.

The client should not need a content type because the response is not allowed by the standard to return any content. 205 is in fact not a reason to call failure block, the success block should be called.

**Comment by kcharwood** [comment] 2016-01-14 16:27
Yep I agree with that @bennibau. I was simply saying I'm assuming the response serializer is failing because there is no matching response content type. That is an _error_ on AF's side.

The surprising issue is the timeout. That doesn't make sense to me.

**Comment by kcharwood** [comment] 2016-01-14 16:27
I'm assigning this one to the 3.1.0 milestone and will try and come up with a patch this week or next.

**Comment by bennibau** [comment] 2016-01-14 16:29
cool! Thank you fixing it. I tried fixing it myself but its somewhere really deep.

**Comment by kcharwood** [comment] 2016-01-14 22:23
I put up #3292 today. Note I was not able to reproduce the timeout issue, but I was able to see the serialization error.

**Comment by kcharwood** [comment] 2016-01-14 22:37
This could alternatively be solved/worked around by using an `AFCompoundSerializer`, and creating an `AFURLResponseSerializer` that has no acceptable content types, and only 204/205 listed as the acceptable status code.

**Comment by kcharwood** [comment] 2016-02-15 14:32
Closing this to direct conversation to #3292

**Closed by kcharwood** 2016-02-15 14:32 UTC
Labels: bug, url session
