### ISSUE TITLE
UIWebView category doesn't call delegate methods

### ISSUE THREAD

**Issue by jlnbuiles** [AFNetworking/AFNetworking#2562] opened 2015-02-13 18:03 UTC

**Comment by jlnbuiles** [comment] 2015-02-13 18:22
Not sure if this by design (since the methods added to the class use completion blocks) or a bug, but after initializing the web view and setting the UIWebViewDelegate, the delegate methods don't seem to be getting called.

**Comment by mattt** [comment] 2015-02-14 18:35
This was originally by design, but revisiting this now, I can't find the harm in having those methods message the delegate. Fixed by 4fbf7c5.

**Closed by mattt** 2015-02-14 18:35 UTC

**Comment by jlnbuiles** [comment] 2015-02-14 21:34
That was fast! 
Thanks :)

best regards,

Julian Builes

US: 816-287-0493; 816-476-2785
Colombia: 319-278-5660




On Sat, Feb 14, 2015 at 10:36 AM -0800, "Mattt Thompson" <notifications@github.com> wrote:












This was originally by design, but revisiting this now, I can't find the harm in having those methods message the delegate. Fixed by 4fbf7c5.
