### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs。

### ISSUE THREAD

**Issue by Yosemite0915** [AFNetworking/AFNetworking#4500] opened 2020-01-07 06:53 UTC
Apple will stop accepting submissions of apps that use UIWebView APIs。

**Comment by Ad1991** [comment] 2020-01-08 06:19
Duplicate of #4428

**Comment by luckychris** [comment] 2020-01-10 06:41
you can download here without dependency, if you want: https://github.com/luckychris/AFNetworking

**Comment by revg75** [comment] 2020-01-13 19:06
Thanks bro.

**Closed** 2020-01-15 16:55 UTC
