### ISSUE TITLE
xcode9 警告问题

### ISSUE THREAD

**Issue by matangfeng** [AFNetworking/AFNetworking#4068] opened 2017-09-27 01:20 UTC
- WARN  | xcodebuild:  AFNetworking/UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m:76:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]
    - WARN  | xcodebuild:  AFNetworking/UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m:97:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]
    - WARN  | xcodebuild:  AFNetworking/UIKit+AFNetworking/UIActivityIndicatorView+AFNetworking.m:106:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]
    - WARN  | xcodebuild:  AFNetworking/UIKit+AFNetworking/UIRefreshControl+AFNetworking.m:75:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]
    - WARN  | xcodebuild:  AFNetworking/UIKit+AFNetworking/UIRefreshControl+AFNetworking.m:95:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]
    - WARN  | xcodebuild:  AFNetworking/UIKit+AFNetworking/UIRefreshControl+AFNetworking.m:104:34: warning: unknown warning group '-Wreceiver-is-weak', ignored [-Wunknown-warning-option]

**Comment by zapjonny** [comment] 2017-09-30 21:12
Duplicate of https://github.com/AFNetworking/AFNetworking/issues/3968#issuecomment-333289103 ?

**Closed** 2017-11-22 19:42 UTC
