### ISSUE TITLE
UIWebView+AFNetworking

### ISSUE THREAD

**Issue by XianRong** [AFNetworking/AFNetworking#4495] opened 2019-12-31 06:03 UTC
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by tfy87happy** [comment] 2020-01-06 02:20
the same

**Comment by lailibo8** [comment] 2020-01-06 08:54
the same

**Comment by SuiTang** [comment] 2020-01-06 09:10
the same

**Comment by wangjin007** [comment] 2020-01-07 06:24
the same , please change thanks

**Comment by Ad1991** [comment] 2020-01-08 06:20
Duplicate of #4428

**Comment by luckychris** [comment] 2020-01-10 06:40
i deleted the dependeny. You can download here if you want: https://github.com/luckychris/AFNetworking

**Closed** 2020-01-15 16:55 UTC
