### ISSUE TITLE
NSURL return value from setDownloadTaskDidFinishDownloadingBlock should be optional / nullable

### ISSUE THREAD

**Issue by alfiehanssen** [AFNetworking/AFNetworking#3104] opened 2015-10-28 16:06 UTC
The method is declared like so in AF v2.6.1: 

```
- (void)setDownloadTaskDidFinishDownloadingBlock:(nullable NSURL * (^)(NSURLSession *session, NSURLSessionDownloadTask *downloadTask, NSURL *location))block;
```

This block is called like so: 

```
#pragma mark - NSURLSessionDownloadDelegate

- (void)URLSession:(NSURLSession *)session
      downloadTask:(NSURLSessionDownloadTask *)downloadTask
didFinishDownloadingToURL:(NSURL *)location
{
    AFURLSessionManagerTaskDelegate *delegate = [self delegateForTask:downloadTask];
    if (self.downloadTaskDidFinishDownloading) {
        NSURL *fileURL = self.downloadTaskDidFinishDownloading(session, downloadTask, location);
        if (fileURL) {
            delegate.downloadFileURL = fileURL;
            NSError *error = nil;
            [[NSFileManager defaultManager] moveItemAtURL:location toURL:fileURL error:&error];
            if (error) {
                [[NSNotificationCenter defaultCenter] postNotificationName:AFURLSessionDownloadTaskDidFailToMoveFileNotification object:downloadTask userInfo:error.userInfo];
            }

            return;
        }
    }

    if (delegate) {
        [delegate URLSession:session downloadTask:downloadTask didFinishDownloadingToURL:location];
    }
}
```

The invocation of the block indicates that the NSURL return value can be nil. And there are cases where we want it to be nil. But consuming this API in Swift the return value is not optional. Forcing us to return a non-nil value i.e. forcing us to invent a bogus value.

**Comment by kcharwood** [comment] 2015-11-03 14:46
dupe of #3043

**Closed by kcharwood** 2015-11-03 14:46 UTC
