### ISSUE TITLE
AFNetworking with Swift give errors in LLDB

### ISSUE THREAD

**Issue by ldiqual** [AFNetworking/AFNetworking#2488] opened 2014-12-30 06:50 UTC
I added AFNetworking as a cocoapods dependency in my Swift project. When debugging with lldb, I'll always get this error:

```
(lldb) po anything
error: Error in auto-import:
failed to get module 'Project' from AST context:
/Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:9: note: in file included from /Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:
#import <AFNetworking/AFNetworking.h>
        ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:34:13: note: in file included from /Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:34:
    #import "AFURLConnectionOperation.h"
            ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFURLConnectionOperation.h:192:1: error: property with 'retain (or strong)' attribute must be of object type
@property (nonatomic, strong) dispatch_queue_t completionQueue;
^
/Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:9: note: in file included from /Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:
#import <AFNetworking/AFNetworking.h>
        ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:34:13: note: in file included from /Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:34:
    #import "AFURLConnectionOperation.h"
            ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFURLConnectionOperation.h:197:1: error: property with 'retain (or strong)' attribute must be of object type
@property (nonatomic, strong) dispatch_group_t completionGroup;
^
/Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:9: note: in file included from /Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:
#import <AFNetworking/AFNetworking.h>
        ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:36:13: note: in file included from /Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:36:
    #import "AFHTTPRequestOperationManager.h"
            ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFHTTPRequestOperationManager.h:154:1: error: property with 'retain (or strong)' attribute must be of object type
@property (nonatomic, strong) dispatch_queue_t completionQueue;
^
/Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:9: note: in file included from /Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:
#import <AFNetworking/AFNetworking.h>
        ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:36:13: note: in file included from /Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:36:
    #import "AFHTTPRequestOperationManager.h"
            ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFHTTPRequestOperationManager.h:159:1: error: property with 'retain (or strong)' attribute must be of object type
@property (nonatomic, strong) dispatch_group_t completionGroup;
^
/Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:9: note: in file included from /Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:
#import <AFNetworking/AFNetworking.h>
        ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:40:13: note: in file included from /Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:40:
    #import "AFURLSessionManager.h"
            ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFURLSessionManager.h:155:1: error: property with 'retain (or strong)' attribute must be of object type
@property (nonatomic, strong) dispatch_queue_t completionQueue;
^
/Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:9: note: in file included from /Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h:7:
#import <AFNetworking/AFNetworking.h>
        ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:40:13: note: in file included from /Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFNetworking.h:40:
    #import "AFURLSessionManager.h"
            ^
/Users/ldiqual/tests/Project/Pods/Headers/Public/AFNetworking/AFURLSessionManager.h:160:1: error: property with 'retain (or strong)' attribute must be of object type
@property (nonatomic, strong) dispatch_group_t completionGroup;
^
failed to import bridging header '/Users/ldiqual/tests/Project/Project/Project-Bridging-Header.h'A fatal parse error has occurred.  LLDB may become unstable; please restart your debug session as soon as possible.
```

[Another user on StackOverflow](https://stackoverflow.com/questions/27282329/afnetworking-with-swift-give-errors-in-lldb) has noticed this issue but I believe Github is the most appropriate place for bugs. I believe this is related to [this `dispatch_queue_t` issue](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-FAQ#im-getting-compiler-errors-about-dispatch_queue_t-being-a-strong-property-whats-up-with-that) in the FAQ.

Can it be due to the swift compiler thinking the target is iOS5?

Here's my podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

pod 'AFNetworking', '2.5.0'
```

And my bridging-header file contains:

```
#import <AFNetworking/AFNetworking.h>
```

**Comment by alexkent** [comment] 2015-01-07 08:22
I see the same issue.

**Comment by RoderickGarztes** [comment] 2015-01-08 14:38
I just tried to create new swift project, and added AFNetworking library with same Podfile above.
It works well...

"Can it be due to the swift compiler thinking the target is iOS5?"
Swift compiler supports only iOS7.0 or later.

And I think this issue came from inappropriate use of lldb commands.

For example
AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
[manager GET:@"http://example.com/resources.json" parameters:nil success:^(AFHTTPRequestOperation *operation, id responseObject) {
    NSLog(@"JSON: %@", responseObject);
} failure:^(AFHTTPRequestOperation *operation, NSError *error) {
    NSLog(@"Error: %@", error);
}];

When you set break point at the first line, and use "po manager".
Then you will get this issue. (I don't think this is an issue. :D ).

After you set break point at the second line, and use "po manager".
It will work.

I am newbiee :dash: , so feel free to correct my opinion.

Regards.
Roderick.

**Comment by ldiqual** [comment] 2015-01-08 20:41
@RoderickGarztes It seems that you are setting the breakpoint inside an Objective-C file. I was talking about a swift project with a breakpoint inside a swift file. Would you mind trying to reproduce in that environment?

**Comment by RoderickGarztes** [comment] 2015-01-09 00:59
Yes, sorry for the above posting.
I tested on swift project, and swift file. lol

let opManager = AFHTTPRequestOperationManager()
        opManager.GET("http://example.com/resources.json", parameters: nil, success: { (operation : AFHTTPRequestOperation!, responseObject : AnyObject!) -> Void in
            println("JSON : \(responseObject)")
            }) { (operation : AFHTTPRequestOperation!, error: NSError!) -> Void in
            println("Error: \(error)")
        }

**Comment by alexkent** [comment] 2015-01-09 13:15
Steps to reproduce

1. Create a new "Single View Application" project with Swift in Xcode 6.1.1
2. Add Podfile

    source 'https://github.com/CocoaPods/Specs.git'
    
    platform :ios, '8.0'
    
    pod 'AFNetworking', '2.5.0'

3. Run `pod install`
4. Add a bridging header to the app, containing: `#import <AFNetworking/AFNetworking.h>`
5. Set a breakpoint at line 14 `super.viewDidLoad()` in ViewController.swift 
6. Run the app
7. At the lldb prompt type `po self`
8. See errors.

No need to write any code (beyond that in the project template).
We are breaking in ViewDidLoad, but pretty much anywhere will show the same errors.

Fix
Changing all instances of `@property (nonatomic, strong) dispatch_queue_t` to `@property (nonatomic, assign) dispatch_queue_t` 

But presumably this will cause compiler warnings in an obj-c project because dispatch_queue_t is / should be treated as an object.

**Comment by ZuYuanZhou** [comment] 2015-01-17 03:58
Same issue here, you can try to run "po xxx" twice, I see the first time is always failed, but the second is OK.

**Comment by moreindirection** [comment] 2015-01-18 19:26
I can also confirm this problem. It's been happening for me since Swift was released. It's not specifically an AFNetworking problem, though (although this is the only place I've ever noticed it). In fact, if your bridging header includes any classes with a property that looks like:

    @property (nonatomic, strong) dispatch_group_t completionGroup;

you'll see these errors whenever you hit a breakpoint in Swift code.

I don't currently have a workaround, but I filed a Radar.

**Comment by grosch** [comment] 2015-02-08 22:55
Would be nice if this would get fixed.  So irritating to have this happen every time I debug something completely unrelated to afnetworking.

**Comment by moreindirection** [comment] 2015-02-08 23:33
I was able to use this as a workaround: http://stackoverflow.com/a/24846028/126855

Works like a charm.

**Comment by mattt** [comment] 2015-02-14 21:44
Fixed by 3a1785c.

**Closed by mattt** 2015-02-14 21:44 UTC

**Comment by moreindirection** [comment] 2015-02-15 13:39
Thanks, @mattt

**Comment by ldiqual** [comment] 2015-02-15 21:14
That's great! Thanks for the fix.
Since the current version 2.5.1 makes it impossible to debug swift projects, can you also bump the version and include your fix? It'd be lovely.

**Comment by jamieomatthews** [comment] 2015-02-24 20:54
@mattt @ldiqual Seconded!  That change would be awesome!  Just waiting for the pod to update

**Comment by mccannmax** [comment] 2015-02-27 07:49
Thirded

**Comment by Jasdev** [comment] 2015-02-27 17:06
@mattt +1 for the bump! Thanks so much!
