### ISSUE TITLE
escape function crashes when escaping long Chinese strings

### ISSUE THREAD

**Issue by TheWalkingDead1024** [AFNetworking/AFNetworking#2958] opened 2015-09-09 04:47 UTC
I am using AFNetworking 2.0. This problem would be easier to reproduce on iOS devices like iphone 5,5s,6. It crashes everytime when I try to encode a POST parameter with more than 280 Chinese characters, and it only gives me an EXC_BAD_ACCESS with no further information. On iPhone 5 with 1GB RAM it can handle about 1300 Chinese characters but still crash if the limitation is exceeded.

For quick reference, this is the escape function I copied from AFURLRequestSerialization.m line 88. 

static NSString * AFPercentEscapedStringFromString(NSString *string) {
    static NSString * const kAFCharactersGeneralDelimitersToEncode = @":#[]@"; // does not include "?" or "/" due to RFC 3986 - Section 3.4
    static NSString * const kAFCharactersSubDelimitersToEncode = @"!$&'()*+,;=";

    NSMutableCharacterSet * allowedCharacterSet = [[NSCharacterSet URLQueryAllowedCharacterSet] mutableCopy];
    [allowedCharacterSet removeCharactersInString:[kAFCharactersGeneralDelimitersToEncode stringByAppendingString:kAFCharactersSubDelimitersToEncode]];

    return [string stringByAddingPercentEncodingWithAllowedCharacters:allowedCharacterSet];
}

 Those are my Chinese strings "一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十一二三四五六七八九十". 
Many Thanks.

**Comment by zhongze** [comment] 2015-09-09 06:38
I have this bug too！

**Comment by lexiaoyao20** [comment] 2015-09-09 07:34
I have this bug too!

FollowmeiOS(16133,0x10b1f1300) malloc: *** error for object 0x7fbc21a0cc00: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

**Comment by kcharwood** [comment] 2015-09-10 13:29
I'm assuming this is related to https://github.com/Alamofire/Alamofire/issues/206

@cnoon I think we may have an issue in both Alamofire and AFNetworking since both frameworks use the same approach now.

@TheWalkingDead1024 @zhongze could you provide more information here? Do you know if this happening in the GM of iOS 9.0? Did you ever file a radar here?

Also, it would be great to write up a quick test for the issue.

**Comment by TheWalkingDead1024** [comment] 2015-09-11 08:16
@kcharwood .Thanks for your reply.It is happening in the iOS8.2, iPhone 5 and iOS8.4, iPhone 5s. I am sorry.What is the meaning of "file a radar"?I will write up a quick test for this issue later, but I don't know how to give a test demo to you.Thanks again.

**Comment by DaVinAhn** [comment] 2015-09-13 06:11
I have this bug too.

**Comment by cnoon** [comment] 2015-09-15 15:53
Oh man this is a bummer. I remember that issue in [Alamofire #206](https://github.com/Alamofire/Alamofire/issues/206). At the time, the Core Foundation calls weren't deprecated. 

We'll have to do some investigation here to see if there is a workaround and we'll definitely need to file a radar or two. Do you have some time to dig into this @kcharwood or do you want me to take it?

**Comment by cnoon** [comment] 2015-09-20 23:16
Okay everyone, I've managed to fix this in Alamofire after a significant amount of investigation. Please refer to [Alamofire #206](https://github.com/Alamofire/Alamofire/issues/206) for more info on how to resolve the issue.

@kcharwood I have added a test to reproduce the issue which should certainly help fix this in AFN as well. AFN should be able to use the exact same batching approach.

**Comment by jkyin** [comment] 2015-10-10 09:49
Thank you @cnoon . You help me  quite a lot. I really appreciate it.

**Comment by kcharwood** [comment] 2015-10-13 18:40
Fixed in #3028

**Closed by kcharwood** 2015-10-13 18:40 UTC
Labels: needs investigation, request serializers
