### ISSUE TITLE
fail to set timeoutInterval when using subclass of AFHTTPRequestOperationManager 

### ISSUE THREAD

**Issue by shuoshi** [AFNetworking/AFNetworking#2563] opened 2015-02-14 03:10 UTC
Dear all

I made a subclass of  AFHTTPRequestOperationManager and wanted to set timeout to 3 seconds.

[netMgr.requestSerializer setTimeoutInterval:3.f];

But it doesn't work.

I can figure out that it's because the auto key value observing returns NO in automaticallyNotifiesObserversForKey when the key is timeoutInterval

Could anyone tell me the reason, or what's the right way to set timeout of request

Much thanks.

Cheers

**Comment by robertmryan** [comment] 2015-02-14 15:51
I agree. Twenty-one days ago, this commit https://github.com/AFNetworking/AFNetworking/commit/0f3829f6afdfa57eced1e80c317e68ca5e5f85d0 turned off automatic observers for these properties, and it's the observer for these properties that ensures that any request serializer properties translate to modification of the `NSMutableURLRequest` object.

I might suggest reopening issue https://github.com/AFNetworking/AFNetworking/issues/2523 which this was intended to address, as there's obviously some unintended consequence of this fix.

**Comment by oztune** [comment] 2015-02-18 20:13
+1. I'm changing the `cachePolicy` of the `requestSerializer` and it's having no effect for the same reason. This seems like a pretty serious issue to go into production unnoticed.

**Comment by soleares** [comment] 2015-02-28 01:54
+1. The following `requestSerializer` properties no longer work because of this change:
- allowsCellularAccess
- cachePolicy
- HTTPShouldHandleCookies
- HTTPShouldUsePipelining
- networkServiceType
- timeoutInterval

**Comment by kgaidis** [comment] 2015-03-02 21:48
+1

**Comment by dmorrow** [comment] 2015-03-09 16:56
+1 
I am unable set HTTPShouldHandleCookies via `self.requestSerializer.HTTPShouldHandleCookies = FALSE;` within a subclass of `TCOHTTPSessionManager` using 2.5.1.
Setting in on custom requests from my `AFJSONRequestSerializer` subclasses works as expected

**Comment by GuillaumeDerivery** [comment] 2015-03-12 19:07
+ 1
I had to subclass AFJSONRequestSerializer to make it working.
Do you have a commit # I can roll back to for the moment please?

**Comment by robertmryan** [comment] 2015-03-14 19:51
@mattt Any thoughts?!?

**Comment by cameronbell** [comment] 2015-03-14 21:33
+1 Had to revert to 2.5.0 because the cachePolicy property was no longer working.

**Comment by shuoshi** [comment] 2015-03-15 01:40
well, here is a workaround I'm using in my project
[apiMgr.requestSerializer willChangeValueForKey:@"timeoutInterval"];
[apiMgr.requestSerializer setTimeoutInterval:1.f];
[apiMgr.requestSerializer didChangeValueForKey:@"timeoutInterval"];

**Comment by mattt** [comment] 2015-03-26 22:00
Fixed by 7d8e286. See #2523 for discussion.

**Closed by mattt** 2015-03-26 22:00 UTC
