### ISSUE TITLE
v2.4.x causes crash on iOS 7.1.x

### ISSUE THREAD

**Issue by mwhuss** [AFNetworking/AFNetworking#2356] opened 2014-10-14 15:18 UTC
After updating to `v2.4.x` I've seen a large amount of crashes from users all running iOS `7.1.x`. There were no issues with `v2.3.x`.

The methods where the crashes occur include:
- [-[AFURLSessionManagerTaskDelegate URLSession:dataTask:didReceiveData:]:160](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLSessionManager.m#L160)
- [-[AFURLSessionManagerTaskDelegate URLSession:task:didCompleteWithError:]:212](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLSessionManager.m#L212)

I'm looking into it more and will try to re-create the issue. I just wanted to get the issue logged.

**Comment by mwhuss** [comment] 2015-01-05 19:10
Nope, we're still seeing this issue for iOS 7 users. We're rolling back to `2.3.1` until we drop iOS 7 support completely.

**Comment by thomasjoulin** [comment] 2015-01-30 07:22
Don't know if it's helpful, but we have the same issue. Rolling back to `2.3.1` since it seems to be working for other people here.

![screen shot 2015-01-30 at 15 20 14](https://cloud.githubusercontent.com/assets/52842/5972396/bcb31292-a893-11e4-988a-f0b0f05d6ce4.png)

**Comment by pocketlim** [comment] 2015-02-03 06:23
This is our 2nd highest crash, 2.5.0, 100% iOS 7. (About to become our highest crash cuz I just fixed our highest one)

![datawithurl](https://cloud.githubusercontent.com/assets/740544/6015496/e8c8be52-ab29-11e4-952e-ebdab16ca6b6.png)

**Comment by skochan** [comment] 2015-02-03 19:39
We're also considering rolling back to 2.3.1 because of the iOS7 crashes.   For those who have done this already, are there any issues?   2.3.1 predates iOS 8, so we're a little concerned about going back to that release.

**Comment by Jeansse** [comment] 2015-02-03 19:41
Didn't have any problems on our side so far - 2.3.1 seems to be rock solid.

Am 03.02.2015 um 20:40 schrieb skochan <notifications@github.com>:

**Comment by skochan** [comment] 2015-02-03 21:39
Thanks for the quick reply.

--

**Comment by podkovyrin** [comment] 2015-07-21 11:21
Same here with 2.5.4 version

**Comment by atcuan** [comment] 2015-07-31 09:15
I got this problem frequency on iOS 7.1
```
malloc: *** error for object 0x7fafc40c6560: pointer being realloc'd was not allocated
*** set a breakpoint in malloc_error_break to debug
```

**Comment by kcharwood** [comment] 2015-10-19 14:52
I'm still not entirely sure of the issue here.

I do want to note that we removing support for `NSURLConnection` in 3.0.0, and relying exclusively on `NSURLSession` since Apple has deprecated `NSURLConnection`, so would go away on that front once you migrate to `AFHTTPSessionManager.`

I'm going to leave this open for now in hopes we can get more information on if this is still a problem or not.

**Comment by Air-Craft** [comment] 2015-11-13 15:18
There's a similar issue involving some of the same lines here: https://github.com/AFNetworking/AFNetworking/issues/2900

**Comment by leslie-lei** [comment] 2016-02-02 20:07
We upgraded to AFNetworking 3.0 and this is still our #1 production crash, 99% on iOS 7. Can we do anything to help moving this bug forward?

**Comment by estebanuribe** [comment] 2016-03-03 23:17
Still a issue for us under AFNetworking 3.0.4 for 98% of users on iOS 7

**Comment by pocketlim** [comment] 2016-03-03 23:21
Guys, this is still a prevalent crash in iOS 7. Anyone even care here? 

![afnetworking_ios7_crash](https://cloud.githubusercontent.com/assets/740544/13513089/844fcee6-e153-11e5-8aee-86dc9797387f.jpg)

**Comment by Jiangmx** [comment] 2016-03-08 01:33
@kcharwood this issue is caused by 
[self.mutableData appendData:data];//line 326 in AFURLSessionManager

In iOS 7.1.x, selector(appendData:) is a asynchronous method. After [NSURLSessionDataTaskDelegate didReceiveData], [NSURLSessionTaskDelegate didCompleteWithError] will be called.While self.mutableData is appending data,if [delegate URLSession:session task:task didCompleteWithError:error] is called and self.mutableData = nil in another thread, origin self.mutableData pointer point to a bad address.

![qq20160308-0 2x](https://cloud.githubusercontent.com/assets/4746814/13589000/72aee888-e50f-11e5-9244-6b54a27ec159.png)

`//checking the systemVersion in line 268 seems fix it.
if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0) {
    self.mutableData = nil;
 }`

Hope that helps!:)

**Comment by estebanuribe** [comment] 2016-04-26 17:29
@Jiangmx Thanks for the insights on that.   Ended up attempting the solution suggested in https://github.com/AFNetworking/AFNetworking/issues/2900 for iOS 7 users and so far the crash numbers seems significantly lower.

**Comment by bigParis** [comment] 2016-06-20 02:00
@estebanuribe it seems no use setting maxConcurrentOperationCount = 1, I got the same crash stack on iOS8.3.

**Comment by bigParis** [comment] 2016-06-20 02:53
if (self.mutableData) {
        data = [self.mutableData copy];
        //We no longer need the reference, so nil it out to gain back some memory.
[self.lock lock];
        self.mutableData = nil;
    }

**Comment by huipengo** [comment] 2016-07-13 02:58
I setting maxConcurrentOperationCount = 1 and write 
if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0) {
        self.mutableData = nil;
}
in line 268 seems fix it.

**Comment by nezhyborets** [comment] 2016-07-28 10:45
So what should we do with it?

**Comment by julianL0veios** [comment] 2016-08-22 06:40
if ([[[UIDevice currentDevice] systemVersion] floatValue] >= 8.0) {
self.mutableData = nil;
} 
seems not work,still got lots of crash.

**Comment by julianL0veios** [comment] 2016-08-23 02:41
<img width="1059" alt="screen shot 2016-08-23 at 10 38 29 am" src="https://cloud.githubusercontent.com/assets/5213620/17878537/11293fbc-691e-11e6-8fda-467dbed4d033.png">
![Uploading Screen Shot 2016-08-23 at 10.39.55 AM.png…]()

**Comment by huang1988519** [comment] 2016-09-14 10:00
`AFURLSessionManager 
#pragma mark - NSURLSessionTaskDelegate

- (void)URLSession:(__unused NSURLSession *)session
              task:(NSURLSessionTask *)task
didCompleteWithError:(NSError *)error
{
...
 //Performance Improvement from #2672
    NSData *data = nil;
    if (self.mutableData) {
        data = [self.mutableData copy];
        //We no longer need the reference, so nil it out to gain back some memory.
        @synchronized (self.mutableData) {
            self.mutableData = nil;
        }
    }
...
}
`
在崩溃的地方加锁，我这边崩溃现象基本没有了。

**Comment by SlaunchaMan** [comment] 2019-02-15 15:40
Closing as this issue is very old. If there are newer crash reports, please open new issues.

**Closed by SlaunchaMan** 2019-02-15 15:40 UTC
Labels: url session
