### ISSUE TITLE
EXC_BAD_ACCESS in not main thread

### ISSUE THREAD

**Issue by storm52** [AFNetworking/AFNetworking#3716] opened 2016-09-30 07:20 UTC
My app easily crashed   on simulator ,mostly just after in 10 times refresh request it crashed ,and in iPhone about 200times got a crash,but after I add a log  before [self af_resume] in AFURLSessionManager in af_resum methord,it stops crash in simulator,I don't know why ,and  I still got this crash on iPhone,can you help me out?
![2016-09-30 2 26 59](https://cloud.githubusercontent.com/assets/8487187/18982608/0a3927d4-871a-11e6-9118-c3519aca2eea.png)

![2016-09-30 2 23 26](https://cloud.githubusercontent.com/assets/8487187/18982547/8feb3b02-8719-11e6-94c6-63b410b2ed10.png)
![2016-09-30 2 20 14](https://cloud.githubusercontent.com/assets/8487187/18982545/8f524492-8719-11e6-899f-ce91e6d7f3da.png)

**Comment by skyline75489** [comment] 2016-10-11 13:23
Might be a duplicate of #3605 . Can you provide more info and maybe a reproducible example?

**Closed** 2017-11-22 21:45 UTC
