### ISSUE TITLE
 Apple will stop accepting submissions of apps that use UIWebView APIs，please change，thank you

### ISSUE THREAD

**Issue by longfaxiang** [AFNetworking/AFNetworking#4498] opened 2020-01-07 04:40 UTC
Apple will stop accepting submissions of apps that use UIWebView APIs，please change，thank you

**Comment by Ad1991** [comment] 2020-01-08 06:20
Duplicate of #4428

**Comment by SuiTang** [comment] 2020-01-08 09:56
mark

**Closed** 2020-01-15 16:54 UTC
