### ISSUE TITLE
AFHTTPSessionManager.requestSerializer set  HTTPHeaderField is invalid 

### ISSUE THREAD

**Issue by caifujiasu** [AFNetworking/AFNetworking#3764] opened 2016-10-21 07:32 UTC
can't set change http request 's params,for example ,"connnection" ,and it  is "keep-alive" default,I want to change it "close",but  don't change.

**Comment by skyline75489** [comment] 2016-10-25 12:52
Show me the code.

**Comment by zhoupIT** [comment] 2016-12-30 05:34
[_instance.requestSerializer setValue:@"close" forHTTPHeaderField:@"Connection"];

**Comment by caifujiasu** [comment] 2016-12-30 05:42
like zhoupIT's code,not any effects.

**Comment by zhoupIT** [comment] 2016-12-30 05:50
why you need to set close?My problem is upload a photo with a interface,memory is increasing.When use other interfaces ,it is no problem,this interface is pass cdn.Who know the problem?

**Comment by zhoupIT** [comment] 2016-12-30 05:53
i think it may be caused by keep-alive,so i want to close it,but it didn't work

**Comment by caifujiasu** [comment] 2016-12-30 05:58
upload a photo ,you can transfer it to NSString ,and struct a post request as parameter

**Comment by zhoupIT** [comment] 2016-12-30 06:03
不是data么,就是我做了个demo,一个接口走了cdn,然后用afn上传图片的时候内存泄漏,换一个不走cdn的接口就没事.cdn是为了加速的,afn需要做什么适配吗

**Closed** 2017-11-22 21:43 UTC
