### ISSUE TITLE
Crash in CFNetwork TCPIOConnection::copyProperty

### ISSUE THREAD

**Issue by KelaKing** [AFNetworking/AFNetworking#3955] opened 2017-05-25 02:10 UTC
### Only occurred on iOS10

| CFNetwork               | TCPIOConnection::copyProperty(__CFString const*) + 44 |
| :---------------------- | ---------------------------------------- |
| CFNetwork               | SPDYConnection::_onqueue_closeStream(SPDYStream*) + 236 |
| CFNetwork               | SPDYConnection::_onqueue_closeStream(SPDYStream*) + 236 |
| CFNetwork               | invocation function for block in SPDYConnection::startEnqueuedStream(SPDYStream*) + 28 |
| libdispatch.dylib       | __dispatch_call_block_and_release + 24   |
| libdispatch.dylib       | __dispatch_client_callout + 16           |
| libdispatch.dylib       | __dispatch_queue_serial_drain + 928      |
| libdispatch.dylib       | __dispatch_queue_invoke + 652            |
| libdispatch.dylib       | __dispatch_root_queue_drain + 572        |
| libdispatch.dylib       | __dispatch_worker_thread3 + 124          |
| libsystem_pthread.dylib | _pthread_wqthread + 1288                 |

**Comment by fingerplay** [comment] 2017-05-27 10:29
I have meet the same problem as u.

**Comment by fingerplay** [comment] 2017-06-05 05:58
@KelaKing which version of AFNetworking are you using?

**Comment by KelaKing** [comment] 2017-06-05 06:22
@fingerplay 2.5.4

**Comment by fingerplay** [comment] 2017-06-11 14:39
@KelaKing I'm using 2.6.3. It seems to be a problem with old version of AFNetworking  . I see Alamofire has the same problem ,but it is resolved after 4.2.0
https://github.com/Alamofire/Alamofire/issues/1886

**Comment by ParsifalC** [comment] 2017-09-08 03:17
Got the same issue here using 2.6.3.Any update for this? @KelaKing @fingerplay

**Comment by fingerplay** [comment] 2017-09-12 06:50
I've update AFNetworking to 4.0.0, but it still crashes, I believe it is an system issue and I hope it will get recovered in iOS 11. I will keep on focusing on it. @ParsifalC

**Comment by SlaunchaMan** [comment] 2017-11-22 20:42
This definitely seems like an iOS issue; closing this for now. If there’s an actual, reproducible bug here feel free to open a new issue. For general help, please ask [on StackOverflow](https://stackoverflow.com/questions/tagged/afnetworking).

**Closed by SlaunchaMan** 2017-11-22 20:42 UTC
