### ISSUE TITLE
download crash in iOS7.1.1 iPod

### ISSUE THREAD

**Issue by circlestriker** [AFNetworking/AFNetworking#3651] opened 2016-08-18 12:38 UTC
in iOS7.1.1, AF3.1.0 crash easily in AFURLSessionManager.m

``` objc
- (void)URLSession:(__unused NSURLSession *)session
          dataTask:(__unused NSURLSessionDataTask *)dataTask
    didReceiveData:(NSData *)data
{
        [self.mutableData appendData:data]; //crash here
}
```

I have to fix it as bellow

``` objc
- (void)URLSession:(__unused NSURLSession *)session
          dataTask:(__unused NSURLSessionDataTask *)dataTask
    didReceiveData:(NSData *)data
{
    @synchronized (self) {
        if(self.mutableData == nil){
            self.mutableData = [NSMutableData data];
        }
        [self.mutableData appendData:data];
    }
}
```

**Comment by circlestriker** [comment] 2016-08-19 03:01
maybe this is another issue:
`/*As the data may be discontiguous, you should use 
 * [NSData enumerateByteRangesUsingBlock:] to access it.
 */
- (void)URLSession:(NSURLSession *)session dataTask:(NSURLSessionDataTask *)dataTask
                                     didReceiveData:(NSData *)data;`
 [self.mutableData appendData:data]; did not handle the discontiguous situation

**Comment by skyline75489** [comment] 2016-10-10 13:54
Seems to be a duplicate of #2900 ?

**Comment by skyline75489** [comment] 2016-10-10 13:55
And (historical) #2356

**Closed** 2017-11-22 21:51 UTC
