### ISSUE TITLE
Crash on AFURLResponseSerialization.m line 235

### ISSUE THREAD

**Issue by mohammad19991** [AFNetworking/AFNetworking#2775] opened 2015-06-09 09:22 UTC
-[AFJSONResponseSerializer responseObjectForResponse:data:error:]

Crashed: com.alamofire.networking.http-request.processing
SIGABRT ABORT at 0x37cbadfc

![screen shot 2015-06-09 at 12 22 22 pm](https://cloud.githubusercontent.com/assets/2028141/8054547/3a0c99ec-0ea2-11e5-9121-cfb5820b6ccd.png)

**Comment by kcharwood** [comment] 2015-06-26 14:29
We're going to need more information on this. Can you reproduce it all?

**Comment by mohammad19991** [comment] 2015-06-26 14:46
Unfortunately it's not easy to reproduce the crash but it's happing with my clients and that's the report we got from Crashlytics, I know its not very helpful! I will let you know if I could reproduce it again, we are trying :)

**Comment by robmaceachern** [comment] 2015-07-16 20:27
`ensureParserFinished` was also failing in #2334. It looks like an Apple bug with no workaround, unfortunately.

**Comment by kcharwood** [comment] 2015-10-19 15:21
It does look related to #2334, which appears to be fixed in 8.2

**Closed by kcharwood** 2015-10-19 15:21 UTC
Labels: response serializers

**Comment by ignazioc** [comment] 2015-11-20 07:45
Same issue here but with iOS9 and AFNetworking 2.6.3.

Any suggestions?

**Comment by revolter** [comment] 2016-09-05 12:40
@kcharwood, Are you sure it's fixed? Asking because there is no confirmation of @ileitch's workaround.
