### ISSUE TITLE
AFHTTPRequestSerializer returns request with incorrect timeoutInterval

### ISSUE THREAD

**Issue by micahhainline** [AFNetworking/AFNetworking#2582] opened 2015-03-05 18:43 UTC
AFHTTPRequestSerializer.requestWithMethod:URLString:parameters:error: returns an NSMutableURLRequest with the default timeoutInterval set, instead of respecting the timeoutInterval that was set on the serializer.

**Comment by danielgomezrico** [comment] 2015-03-05 19:29
+1 Same for me

**Comment by mattt** [comment] 2015-03-06 14:36
Duplicate of #2563.

**Closed by mattt** 2015-03-06 14:36 UTC

**Comment by danielgomezrico** [comment] 2015-03-06 15:27
is it a duplicate? 

I'm not subclassing AFHTTPRequestOperationManager and it happens too.

**Comment by mattt** [comment] 2015-03-06 15:57
Yes, it's the same underlying cause.

**Comment by danielgomezrico** [comment] 2015-03-06 19:02
Ok, I didn't said anything ;)
