### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView

### ISSUE THREAD

**Issue by vibhootitatva** [AFNetworking/AFNetworking#4499] opened 2020-01-07 04:58 UTC
Please update it.

**Comment by Ad1991** [comment] 2020-01-08 06:20
Duplicate of #4428

**Comment by tatvarajendra** [comment] 2020-01-08 06:25
When can we accept the updated library?

**Comment by luckychris** [comment] 2020-01-10 06:40
now and here :) . https://github.com/luckychris/AFNetworking

**Comment by vibhootitatva** [comment] 2020-01-10 14:10
Hi, Thanks for the quick response. Its really appreciated and helpful.

I have goes through your commit for this, it seems you removed the file which were using the webview. Will it effect anything? Any other changes for that?

What you guys have used instead of UIWebview?

**Comment by luckychris** [comment] 2020-01-10 14:27
I am not using UIWebview, but i think you can use WKWebview....see e.g. here: https://www.hackingwithswift.com/example-code/wkwebview/whats-the-difference-between-uiwebview-and-wkwebview

**Comment by sauchye** [comment] 2020-01-11 11:56
thanks @luckychris

**Closed** 2020-01-15 16:55 UTC

**Comment by vibhootitatva** [comment] 2020-01-16 04:42
@luckychris 
It giving version with the webview if I try to install with pod 'AFNetworking', '~> 3.0' .
and If I download the code you shared then its correct, No webview. 

How can I download without Webview using pod? 

Also my previous question on webview is regarding the files of AFNetworking. Like as the file with UIWebview was removed, but no any other files added on behalf of that.
