### ISSUE TITLE
DOC need fix

### ISSUE THREAD

**Issue by weng1250** [AFNetworking/AFNetworking#3449] opened 2016-04-21 09:18 UTC
http://cocoadocs.org/docsets/AFNetworking/3.0.4/
URL FORM PARAMETER ENCODING

[[AFHTTPRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters];
->
[[AFHTTPRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters error:nil];

and
JSON PARAMETER ENCODING

[[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters];
->
[[AFJSONRequestSerializer serializer] requestWithMethod:@"POST" URLString:URLString parameters:parameters error:nil];

**Comment by kcharwood** [comment] 2016-05-06 14:17
dupe of #3411

**Closed by kcharwood** 2016-05-06 14:17 UTC
